### ISSUE TITLE
Unattended upgrade is wrong

### ISSUE THREAD

**Issue by karan** [flxn/tor-relay-configurator#20]
On Ubuntu 18.04.4 LTS.

With the existing config, I get this errors.

```
# unattended-upgrade -v -d --dry-run
Unable to parse Unattended-Upgrade::Allowed-Origins.
Traceback (most recent call last):
  File "/usr/bin/unattended-upgrade", line 2193, in <module>
    sys.exit(main(options))
  File "/usr/bin/unattended-upgrade", line 1745, in main
    allowed_origins = get_allowed_origins()
  File "/usr/bin/unattended-upgrade", line 546, in get_allowed_origins
    allowed_origins = get_allowed_origins_legacy()
  File "/usr/bin/unattended-upgrade", line 525, in get_allowed_origins_legacy
    (distro_id, distro_codename) = s.split()
ValueError: not enough values to unpack (expected 2, got 1)
```

The one that works for me is:

```
Unattended-Upgrade::Origins-Pattern {
        "origin=Debian,codename=${distro_codename},label=Debian-Security";
	"origin=TorProject";
};
```

**Comment by flxn** [comment]
Thank you, I updated the config file.
